function generateHelm(input = {}, sizing = {}) {
  return `# values.yaml generated by Smart Architecture Advisor v3.3

replicaCount: ${sizing.backend_pods || 2}

image:
  repository: yourdockerhub/backend
  tag: v3.3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources:
  requests:
    cpu: "${sizing.cpu_per_pod || '500m'}"
    memory: "${sizing.memory_per_pod || '512Mi'}"
  limits:
    cpu: "1000m"
    memory: "1Gi"

autoscaling:
  enabled: true
  minReplicas: ${sizing.hpa_min || 2}
  maxReplicas: ${sizing.hpa_max || 6}
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: app.example.com
      paths:
        - path: /
          pathType: Prefix

env:
  NODE_ENV: production
  PORT: 3000

readinessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10
`;
}

module.exports = {
  generateHelm
};